// تسميات الحقول بالعربية
export const fieldLabels: Record<string, string> = {
  'i_accountno': 'رقم الحساب',
  'I_type': 'النوع',
  'CON_NAME': 'اسم المستهلك',
  'REC_NO': 'رقم السجل',
  'i_serial': 'التسلسل',
  'i_name': 'الاسم',
  'i_streetno': 'رقم الشارع',
  'i_streetname': 'اسم الشارع',
  'i_houseno': 'رقم المنزل',
  'i_address': 'العنوان',
  'i_meter': 'رقم العداد',
  'i_meter_date': 'تاريخ العداد',
  'i_meter_old': 'العداد القديم',
  'i_cust': 'العميل',
  'i_overtype': 'نوع التجاوز',
  'i_overtypen': 'رقم نوع التجاوز',
  'i_avgconsum': 'متوسط الاستهلاك',
  'i_avgdt': 'تاريخ المتوسط',
  'i_instalno': 'رقم التركيب',
  'i_enterdte': 'تاريخ الإدخال',
  'i_entername': 'اسم المدخل',
  'I_read': 'القراءة',
  'I_read_dt': 'تاريخ القراءة',
  'i_custcode': 'رمز العميل',
  'i_metercout': 'عدد العدادات',
  'i_facter': 'المعامل',
  'i_unit1': 'الوحدة 1',
  'i_unitp1': 'سعر الوحدة 1',
  'i_unit2': 'الوحدة 2',
  'i_unitp2': 'سعر الوحدة 2',
  'i_unit3': 'الوحدة 3',
  'i_unitp3': 'سعر الوحدة 3',
  'i_unit4': 'الوحدة 4',
  'i_unitp4': 'سعر الوحدة 4',
  'i_unit5': 'الوحدة 5',
  'i_unitp5': 'سعر الوحدة 5',
  'i_unit6': 'الوحدة 6',
  'i_unitp6': 'سعر الوحدة 6',
  'i_unit7': 'الوحدة 7',
  'i_unitp7': 'سعر الوحدة 7',
  'i_unit8': 'الوحدة 8',
  'i_unitp8': 'سعر الوحدة 8',
  'i_unit9': 'الوحدة 9',
  'i_unitp9': 'سعر الوحدة 9',
  'i_txtuser': 'المستخدم',
  'i_txtusern': 'رقم المستخدم',
  'i_txtread': 'قارئ النص',
  'i_txtreadn': 'رقم قارئ النص',
  'i_optionn': 'الخيار',
  'i_txtcenta': 'المركز',
  'i_amount': 'المبلغ',
  'i_sector': 'القطاع',
  'i_end_time': 'وقت الانتهاء',
  'i_trnsrent': 'الإيجار',
  'i_trnsrent_dte': 'تاريخ الإيجار',
  'phase': 'المرحلة'
}

// الحقول المهمة للعرض السريع
export const importantFields = [
  'i_accountno',
  'I_type', 
  'i_entername',
  'I_read',
  'I_read_dt',
  'i_enterdte',
  'i_end_time',
  'i_amount'
]

// أنواع البيانات
export const fieldTypes: Record<string, 'text' | 'number' | 'date' | 'time'> = {
  'i_accountno': 'text',
  'I_type': 'number',
  'i_enterdte': 'date',
  'I_read_dt': 'date',
  'i_end_time': 'time',
  'I_read': 'number',
  'i_amount': 'number'
}
